services:
  frontend:
    image: ghcr.io/nakakonakako/price-memo-frontend:latest
    container_name: price-frontend
    volumes:
      - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - price-backend
    networks:
      - default
      - edge

  price-backend:
    image: ghcr.io/nakakonakako/price-memo-backend:latest
    container_name: price-backend
    expose:
      - "8000"
    env_file:
      - ./.env

networks:
  edge:
    external: true
